name: CI for Diabetes Prediction Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      # Run Streamlit in Headless Mode
      - name: Run Streamlit in Headless Mode
        run: |
          streamlit run temp.py --server.headless true &
          sleep 10
          pkill streamlit
